export const defaultFormValues = {
  farm_name: "North Field",
  location: "Des Moines, IA",
  acreage: 120,
  crop_options: ["Corn", "Soybeans"],
  soil_moisture: "Medium",
  field_readiness: "Ready",
};

export const demoAnalysis = {
  resolved_location: {
    display_name: "Des Moines, Iowa, United States",
    latitude: 41.5868,
    longitude: -93.625,
    state: "Iowa",
    country: "United States",
    timezone: "America/Chicago",
  },
  data_sources: {
    geocoding: "fallback",
    weather: "fallback",
    soil: "fallback",
    market: "fallback",
    ag_context: "fallback",
  },
  recommendation: {
    action: "Plant corn within the next 5 days",
    crop: "Corn",
    timing: "Within 5 days",
    confidence: 78,
    summary:
      "Corn is the strongest near-term planting option because field conditions are workable, weather is favorable, and market signals are currently stronger than soybeans. This recommendation balances execution speed with manageable risk.",
    why_crop:
      "Corn keeps the best combined weather and market score in the baseline demo scenario, with solid regional fit.",
    why_timing:
      "The current field window is still open, and waiting exposes the plan to higher rainfall risk later in the week.",
    operational_note:
      "Use the current workable window while monitoring rainfall later in the week.",
  },
  confidence: 78,
  confidence_label: "high",
  confidence_breakdown: {
    weather: 0.82,
    soil: 0.74,
    market: 0.71,
    regional_fit: 0.78,
    timing: 0.84,
  },
  signals: {
    local: {
      label: "Local Conditions",
      status: "Favorable",
      score: 82,
      summary: "Temperatures and field readiness support planting this week.",
    },
    market: {
      label: "Market Conditions",
      status: "Corn stronger",
      score: 74,
      summary: "Corn pricing and momentum are modestly stronger than soybeans.",
    },
    risk: {
      label: "Risk Level",
      status: "Moderate",
      score: 38,
      summary: "Rain risk increases later in the week if planting is delayed.",
    },
  },
  top_reasons: [
    "Field readiness is strong enough to support planting now.",
    "Corn has the strongest combined weather and market score.",
    "Waiting increases exposure to rain disruption.",
  ],
  key_risks: [
    "Rain probability rises after several days.",
    "Market advantage over soybeans is modest, not overwhelming.",
    "Short weather windows can still compress field operations.",
  ],
  scenarios: [
    {
      label: "Plant corn now",
      score: 84,
      risk_level: "Medium",
      summary: "Best balance of timing, field readiness, and market strength.",
      crop: "Corn",
      delay_days: 0,
      scores: {
        weather: 18,
        soil: 15,
        market: 15,
        regional_fit: 10,
        timing: 17,
        risk_penalty: -7,
        preference_bonus: 0,
      },
      delta_from_best: 0,
    },
    {
      label: "Wait 3 days",
      score: 71,
      risk_level: "Medium-High",
      summary: "Still viable, but weather uncertainty begins to increase.",
      crop: "Corn",
      delay_days: 3,
      scores: {
        weather: 16,
        soil: 15,
        market: 15,
        regional_fit: 10,
        timing: 13,
        risk_penalty: -8,
        preference_bonus: 0,
      },
      delta_from_best: 13,
    },
    {
      label: "Plant soybeans now",
      score: 68,
      risk_level: "Medium",
      summary: "Possible, but market outlook is weaker than corn.",
      crop: "Soybeans",
      delay_days: 0,
      scores: {
        weather: 17,
        soil: 14,
        market: 12,
        regional_fit: 9,
        timing: 15,
        risk_penalty: -9,
        preference_bonus: 0,
      },
      delta_from_best: 16,
    },
    {
      label: "Wait 7 days",
      score: 57,
      risk_level: "High",
      summary: "Delay creates more timing and rainfall risk.",
      crop: "Corn",
      delay_days: 7,
      scores: {
        weather: 13,
        soil: 15,
        market: 15,
        regional_fit: 10,
        timing: 10,
        risk_penalty: -6,
        preference_bonus: 0,
      },
      delta_from_best: 27,
    },
  ],
  decision_window: [
    { day: 0, label: "Now", score: 84, risk: "medium", crop: "Corn" },
    { day: 1, label: "1 day", score: 82, risk: "medium", crop: "Corn" },
    { day: 2, label: "2 days", score: 79, risk: "medium", crop: "Corn" },
    { day: 3, label: "3 days", score: 71, risk: "medium-high", crop: "Corn" },
    { day: 4, label: "4 days", score: 67, risk: "medium-high", crop: "Corn" },
    { day: 5, label: "5 days", score: 63, risk: "high", crop: "Corn" },
    { day: 6, label: "6 days", score: 60, risk: "high", crop: "Corn" },
    { day: 7, label: "7 days", score: 57, risk: "high", crop: "Corn" },
  ],
  what_would_change: [
    "If rainfall risk eases by about 15%, waiting briefly becomes less necessary and planting immediately stays in front.",
    "If field readiness slips back to Nearly Ready, the advantage of planting now narrows quickly.",
    "If corn market support softens, soybeans become more competitive.",
  ],
  charts: {
    price_trend: [
      { day: "Mon", Corn: 4.62, Soybeans: 11.1, Wheat: 5.48 },
      { day: "Tue", Corn: 4.68, Soybeans: 11.03, Wheat: 5.44 },
      { day: "Wed", Corn: 4.73, Soybeans: 10.98, Wheat: 5.4 },
      { day: "Thu", Corn: 4.77, Soybeans: 10.95, Wheat: 5.37 },
      { day: "Fri", Corn: 4.81, Soybeans: 10.92, Wheat: 5.35 },
    ],
    weather_forecast: [
      { day: "Mon", temp: 61, rain: 10 },
      { day: "Tue", temp: 64, rain: 15 },
      { day: "Wed", temp: 66, rain: 20 },
      { day: "Thu", temp: 63, rain: 30 },
      { day: "Fri", temp: 59, rain: 50 },
      { day: "Sat", temp: 57, rain: 60 },
      { day: "Sun", temp: 58, rain: 35 },
    ],
  },
  base_context: null,
};
